baseURL = "https://www.andyls.co.uk/"
languageCode = "en-gb"
title = "Andrew Lamzed-Short"
theme = "andyls"

[params]
  author = "Andrew Lamzed-Short"

[taxonomies]
  category = "categories"
  tags = "tags"

[permalinks]
  blog = "/blog/:year/:month/:slug/"
  tags = "/tag/:slug/"

[menu]
  [[menu.main]]
  name = "About"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Blog"
  url = "/blog/"
  weight = 2

  [[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 3