baseURL = "https://www.andyls.co.uk/"
languageCode = "en-gb"
title = "Andrew Lamzed-Short"
theme = "bare"
paginate = 3

[taxonomies]
  tag = "tags"
  series = "series"

# [permalinks]
#   blog = "/blog/:year/:month/:slug/"
#   tags = "/tag/:slug/"

[params]
  mainSections = ["posts"]
  author = "Andrew Lamzed-Short"
  email = "me@andyls.co.uk"
  description = "Computer Science PhD Student at the University of Warwick"
  #postcss = true
  # Include the author name in the <title> of articles
  includeAuthorInTitle = true
  disableAttribution = true

[[params.social]]
  icon = "github"
  title = "GitHub"
  url = "https://github.com/andylshort/"

[[params.social]]
  icon = "twitter"
  title = "Twitter"
  url = "https://twitter.com/andylshort/"

[[params.social]]
  icon = "linkedin"
  title = "LinkedIn"
  url = "https://linkedin.com/in/andy-l-short"